[package]
edition = "2021"
name = "json_macro"
version = "1.0.0"
description = "Macros for automatically deriving serialize and deserialize"

authors = { workspace = true }
license-file = { workspace = true }

[lib]
proc-macro = true
